/**
 * Application-wide TypeScript types.
 *
 * Role and user types are defined here.
 * These are the authoritative type definitions for authorization logic.
 *
 * Database types will be generated by Supabase CLI and placed in:
 *   src/lib/supabase/types.ts  (Phase 1/2 — after schema is created)
 */

export type UserRole = "student" | "faculty" | "coordinator" | "admin";

export interface UserProfile {
  id: string;
  role: UserRole;
  full_name: string;
  avatar_url: string | null;
  phone: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * Pagination parameters used consistently across all list endpoints.
 * Default page size is 20 per the finalized architecture decisions.
 */
export interface PaginationParams {
  page: number;
  pageSize: number;
}

/**
 * Standard paginated response shape for all list API responses.
 */
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

/**
 * Standard API error shape returned from Route Handlers.
 */
export interface ApiError {
  error: string;
  code?: string;
}
